# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap_test_2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePriceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('food_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPriceDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('food_id', models.IntegerField()),
                ('user_input', models.FloatField()),
                ('s0_p0', models.IntegerField()),
                ('s0_p1', models.IntegerField()),
                ('s0_p2', models.IntegerField()),
                ('s0_p3', models.IntegerField()),
                ('s0_p4', models.IntegerField()),
                ('s0_p5', models.IntegerField()),
                ('s1_p0', models.IntegerField()),
                ('s1_p1', models.IntegerField()),
                ('s1_p2', models.IntegerField()),
                ('s1_p3', models.IntegerField()),
                ('s1_p4', models.IntegerField()),
                ('s1_p5', models.IntegerField()),
                ('s2_p0', models.IntegerField()),
                ('s2_p1', models.IntegerField()),
                ('s2_p2', models.IntegerField()),
                ('s2_p3', models.IntegerField()),
                ('s2_p4', models.IntegerField()),
                ('s2_p5', models.IntegerField()),
                ('s3_p0', models.IntegerField()),
                ('s3_p1', models.IntegerField()),
                ('s3_p2', models.IntegerField()),
                ('s3_p3', models.IntegerField()),
                ('s3_p4', models.IntegerField()),
                ('s3_p5', models.IntegerField()),
                ('s4_p0', models.IntegerField()),
                ('s4_p1', models.IntegerField()),
                ('s4_p2', models.IntegerField()),
                ('s4_p3', models.IntegerField()),
                ('s4_p4', models.IntegerField()),
                ('s4_p5', models.IntegerField()),
                ('s5_p0', models.IntegerField()),
                ('s5_p1', models.IntegerField()),
                ('s5_p2', models.IntegerField()),
                ('s5_p3', models.IntegerField()),
                ('s5_p4', models.IntegerField()),
                ('s5_p5', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='snaplocations',
            name='double_value',
            field=models.CharField(max_length=5000),
        ),
    ]
