# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snap_test_2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multipliers',
            old_name='coefficient',
            new_name='multiplier',
        ),
        migrations.RenameField(
            model_name='multipliers',
            old_name='var_name',
            new_name='price_level',
        ),
        migrations.AddField(
            model_name='multipliers',
            name='store_category',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
