# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap_test_2', '0002_foodprices'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodprices',
            name='food_type',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
