# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodprices',
            name='food_price',
            field=models.FloatField(),
        ),
    ]
